//! Pure prompt-settings logic: generated init scripts and the marked block in
//! a user's startup file.
use compi_protocol::prompt::{PromptProvider, PromptScope, PromptShell, PromptState};

pub(super) const BLOCK_BEGIN: &str = "# >>> compi prompt >>>";
pub(super) const BLOCK_END: &str = "# <<< compi prompt <<<";
const GENERATED: &str = "# Generated by Compi prompt settings. Compi replaces this file when you apply prompt settings.";

pub(super) const fn config_extension(provider: PromptProvider) -> &'static str {
    match provider {
        PromptProvider::OhMyPosh => "omp.json",
        PromptProvider::Starship => "starship.toml",
    }
}

pub(super) const fn scope_name(scope: PromptScope) -> &'static str {
    match scope {
        PromptScope::Compi => "compi",
        PromptScope::Normal => "normal",
    }
}

pub(super) fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// The init script Compi sources for one scope and shell.
pub(super) fn init_script(
    provider: PromptProvider,
    binary: &str,
    shell: PromptShell,
    config: &str,
) -> String {
    let snapshot = match shell {
        PromptShell::Bash => {
            "if declare -F _compi_prompt_snapshot >/dev/null 2>&1; then _compi_prompt_snapshot; fi"
        }
        PromptShell::Zsh => {
            "if (( ${+functions[_compi_prompt_snapshot]} )); then _compi_prompt_snapshot; fi"
        }
    };
    let binary = shell_quote(binary);
    let config = shell_quote(config);
    let shell = shell.name();
    let init = match provider {
        PromptProvider::OhMyPosh => {
            format!("    eval \"$({binary} init {shell} --config {config})\"")
        }
        PromptProvider::Starship => {
            format!("    export STARSHIP_CONFIG={config}\n    eval \"$({binary} init {shell})\"")
        }
    };
    format!("{GENERATED}\n{snapshot}\nif [ -x {binary} ]; then\n{init}\nfi\n")
}

/// The script running Compi shells source after a live reload; `None` when no
/// managed prompt remains, so they return to their own prompt.
pub(super) fn live_script(shell: PromptShell, state: &PromptState, base: &str) -> Option<String> {
    let mut script = String::new();
    if state
        .normal
        .as_ref()
        .is_some_and(|applied| applied.shell == Some(shell))
    {
        let path = shell_quote(&format!("{base}/normal.{}", shell.name()));
        script.push_str(&format!("[ ! -f {path} ] || . {path}\n"));
    }
    if state.compi.is_some() {
        let path = shell_quote(&format!("{base}/compi.{}", shell.name()));
        script.push_str(&format!("[ ! -f {path} ] || . {path}\n"));
    }
    (!script.is_empty()).then(|| format!("{GENERATED}\n{script}"))
}

pub(super) fn block(shell: PromptShell) -> String {
    let path = format!("$HOME/.compi/prompt/normal.{}", shell.name());
    format!(
        "{BLOCK_BEGIN}\n# Managed by Compi prompt settings. Turn it off there, or delete this block.\nif [ -f \"{path}\" ]; then . \"{path}\"; fi\n{BLOCK_END}\n"
    )
}

fn block_range(lines: &[&str]) -> Option<(usize, usize)> {
    let start = lines
        .iter()
        .position(|line| line.trim_end() == BLOCK_BEGIN)?;
    let end = lines[start..]
        .iter()
        .position(|line| line.trim_end() == BLOCK_END)?;
    Some((start, start + end))
}

/// The marked block in `content`, if any, including its trailing newline.
pub(super) fn find_block(content: &str) -> Option<String> {
    let lines: Vec<&str> = content.split_inclusive('\n').collect();
    let (start, end) = block_range(&lines)?;
    let mut block: String = lines[start..=end].concat();
    if !block.ends_with('\n') {
        block.push('\n');
    }
    Some(block)
}

/// Replace Compi's block in place, or append it, leaving every other line as is.
pub(super) fn with_block(content: &str, block: &str) -> String {
    let lines: Vec<&str> = content.split_inclusive('\n').collect();
    if let Some((start, end)) = block_range(&lines) {
        let mut output: String = lines[..start].concat();
        output.push_str(block);
        output.push_str(&lines[end + 1..].concat());
        return output;
    }
    let mut output = content.to_owned();
    if !output.is_empty() && !output.ends_with('\n') {
        output.push('\n');
    }
    output.push_str(block);
    output
}

pub(super) fn without_block(content: &str) -> String {
    let lines: Vec<&str> = content.split_inclusive('\n').collect();
    match block_range(&lines) {
        Some((start, end)) => {
            let mut output: String = lines[..start].concat();
            output.push_str(&lines[end + 1..].concat());
            output
        }
        None => content.to_owned(),
    }
}

/// A single-hunk line diff with two lines of context.
pub(super) fn line_diff(old: &str, new: &str) -> String {
    let old: Vec<&str> = old.lines().collect();
    let new: Vec<&str> = new.lines().collect();
    let prefix = old
        .iter()
        .zip(&new)
        .take_while(|(left, right)| left == right)
        .count();
    let suffix = old[prefix..]
        .iter()
        .rev()
        .zip(new[prefix..].iter().rev())
        .take_while(|(left, right)| left == right)
        .count();
    let context = prefix.saturating_sub(2);
    let old_end = (old.len() - suffix + 2).min(old.len());
    let new_end = (new.len() - suffix + 2).min(new.len());
    let mut diff = format!(
        "@@ -{},{} +{},{} @@\n",
        context + 1,
        old_end - context,
        context + 1,
        new_end - context
    );
    for line in &old[context..prefix] {
        diff.push_str(&format!(" {line}\n"));
    }
    for line in &old[prefix..old.len() - suffix] {
        diff.push_str(&format!("-{line}\n"));
    }
    for line in &new[prefix..new.len() - suffix] {
        diff.push_str(&format!("+{line}\n"));
    }
    for line in &old[old.len() - suffix..old_end] {
        diff.push_str(&format!(" {line}\n"));
    }
    diff
}

/// The configuration file an `oh-my-posh init` line passes with `--config`.
pub(super) fn existing_omp_config(line: &str, home: &str) -> Option<String> {
    let tokens: Vec<&str> = line.split_whitespace().collect();
    let init = tokens.iter().position(|token| *token == "init")?;
    let mut value = None;
    for (index, token) in tokens.iter().enumerate().skip(init + 1) {
        if let Some(rest) = token.strip_prefix("--config=") {
            value = Some(rest);
        } else if (*token == "--config" || *token == "-c") && index + 1 < tokens.len() {
            value = Some(tokens[index + 1]);
        }
    }
    let value = value?
        .trim_end_matches([')', '"', '\'', ';', '`'])
        .trim_start_matches(['"', '\'']);
    let path = if let Some(rest) = value.strip_prefix("~/") {
        format!("{home}/{rest}")
    } else if let Some(rest) = value
        .strip_prefix("$HOME/")
        .or_else(|| value.strip_prefix("${HOME}/"))
    {
        format!("{home}/{rest}")
    } else {
        value.to_owned()
    };
    (path.starts_with('/') && !path.contains('$')).then_some(path)
}

/// A readable name for a theme file, such as `capr4n` for `capr4n.omp.json`.
pub(super) fn style_label(path: &str) -> String {
    let name = path.rsplit('/').next().unwrap_or(path);
    for suffix in [
        ".omp.json",
        ".omp.yaml",
        ".omp.yml",
        ".omp.toml",
        ".json",
        ".yaml",
        ".yml",
        ".toml",
    ] {
        if let Some(stem) = name.strip_suffix(suffix) {
            return stem.to_owned();
        }
    }
    name.to_owned()
}

#[cfg(test)]
mod tests {
    use super::*;
    use compi_protocol::prompt::{PromptApplied, PromptConfig, PromptStyle};

    #[test]
    fn block_is_replaced_in_place_appended_once_and_removed_without_touching_other_lines() {
        let user = "export A=1\neval \"$(oh-my-posh init zsh)\"";
        let added = with_block(user, &block(PromptShell::Zsh));
        assert!(
            added.starts_with(
                "export A=1\neval \"$(oh-my-posh init zsh)\"\n# >>> compi prompt >>>\n"
            )
        );
        assert_eq!(with_block(&added, &block(PromptShell::Zsh)), added);
        let middle = format!("{added}alias ll='ls -l'\n");
        let switched = with_block(&middle, &block(PromptShell::Bash));
        assert!(switched.contains("normal.bash") && !switched.contains("normal.zsh"));
        assert!(switched.ends_with("alias ll='ls -l'\n"));
        assert_eq!(
            without_block(&middle),
            "export A=1\neval \"$(oh-my-posh init zsh)\"\nalias ll='ls -l'\n"
        );
        assert_eq!(find_block(&middle), Some(block(PromptShell::Zsh)));
        assert_eq!(without_block(user), user);
    }

    #[test]
    fn diff_shows_only_the_changed_lines_with_context() {
        let old = "a\nb\nc\nd\n";
        let new = "a\nb\nc\nX\nY\nd\n";
        assert_eq!(line_diff(old, new), "@@ -2,3 +2,5 @@\n b\n c\n+X\n+Y\n d\n");
        assert_eq!(line_diff("", "x\n"), "@@ -1,0 +1,1 @@\n+x\n");
    }

    #[test]
    fn existing_omp_config_is_read_from_common_init_lines() {
        let home = "/home/me";
        for (line, expected) in [
            (
                "eval \"$(oh-my-posh init zsh --config ~/.cache/oh-my-posh/themes/capr4n.omp.json)\"",
                Some("/home/me/.cache/oh-my-posh/themes/capr4n.omp.json"),
            ),
            (
                "eval \"$(oh-my-posh init bash --config=\"$HOME/x.omp.yaml\")\"",
                Some("/home/me/x.omp.yaml"),
            ),
            (
                "eval \"$(oh-my-posh init bash -c '/etc/t.json')\"",
                Some("/etc/t.json"),
            ),
            ("eval \"$(oh-my-posh init bash)\"", None),
            (
                "eval \"$(oh-my-posh init bash --config https://x/t.json)\"",
                None,
            ),
            ("eval \"$(oh-my-posh init bash --config $THEME)\"", None),
        ] {
            assert_eq!(
                existing_omp_config(line, home).as_deref(),
                expected,
                "{line}"
            );
        }
    }

    #[test]
    fn live_script_loads_normal_only_for_its_shell_before_the_compi_prompt() {
        let applied = |shell| PromptApplied {
            config: PromptConfig {
                provider: PromptProvider::Starship,
                style: PromptStyle::Default,
            },
            shell,
            startup_file: None,
            applied_at_ms: 1,
        };
        let state = PromptState {
            compi: Some(applied(None)),
            normal: Some(applied(Some(PromptShell::Zsh))),
        };
        let zsh = live_script(PromptShell::Zsh, &state, "/h/.compi/prompt").unwrap();
        let normal = zsh.find("normal.zsh").unwrap();
        assert!(normal < zsh.find("compi.zsh").unwrap());
        let bash = live_script(PromptShell::Bash, &state, "/h/.compi/prompt").unwrap();
        assert!(!bash.contains("normal.") && bash.contains("compi.bash"));
        assert_eq!(
            live_script(PromptShell::Bash, &PromptState::default(), "/h"),
            None
        );
    }

    #[test]
    fn init_script_quotes_paths_and_guards_a_missing_provider() {
        let script = init_script(
            PromptProvider::OhMyPosh,
            "/opt/it's/oh-my-posh",
            PromptShell::Bash,
            "/home/me/.compi/prompt/compi.omp.json",
        );
        assert!(script.contains("if [ -x '/opt/it'\\''s/oh-my-posh' ]; then"));
        assert!(script.contains("init bash --config '/home/me/.compi/prompt/compi.omp.json'"));
    }
}
